let heroImage;
let gameOverImage;
let soundTrack;
let gameOverSoundTrack;
let hero;
let jumpSoundTrack;
const enemies = [];
let score;
let game;
let home;
let homeImage;
let erinFont;
let buttomManager;
let currentScene;
let heartImage;
let life;
let cartucho;
let virtualCanvas;
